---
slug: back-template
title: JavaSE基础-异常
author: Lin
author_title: xiaominglin789
author_url: https://github.com/xiaominglin789/lin-blog
author_image_url: https://avatars2.githubusercontent.com/u/74356262?s=400&u=51bc963a308dd3748ba5133c9cfd29eb3bc0c207&v=4
tags: [back, JavaSE]
---

## 异常
- Error     awt、jvm级别的错误
- Exceotion 代码界别的异常
- 异常处理
	+ try catch 捕获异常
	+ 捕获多个异常： 从小到大
	+ 快捷键: 选中监控区域 + "ctrl" + "alt" + "t"
- 主动抛出异常: throw, 在方法内抛出
- 主动在方法上抛出异常


<!--truncate-->


```java
# 1.在方法中抛出
try {
	// 监控区域
} catch (较小的异常类型 e) {
	// 捕获到异常
} catch (大的异常类型 e) {
	// 捕获到异常
} finally {
	// 处理善后工作
	// 一定会被执行的代码
}

# 2.在方法上抛出异常
public void upLoad(String path) throws Exception {
	
}
```



##### 自定义异常
- 继承 `Exception`
- 重写toString()
- try...catch

```java
public class APIException extends Exception {
    private String message;
    private int errorCode;
    public APIException(String message, int errorCode) {
        super(message);
        this.message = message;
        this.errorCode = errorCode;
    }

    @Override
    public String toString() {
        return "重写异常提示信息";
    }
}
```

